DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS scores;

CREATE TABLE players (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    groupme_id TEXT UNIQUE NOT NULL,
    username TEXT NOT NULL
);

CREATE TABLE scores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER NOT NULL,
  wordle_id INTEGER NOT NULL,
  score INTEGER NOT NULL,
  FOREIGN KEY (player_id) REFERENCES players (id)
);